/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 05/04/2020
 ***********************************************************************************************/

#include "lenworks_interface_a_interface.h"

#define MAX_MESSAGE_SIZE 256

//
// Callback function declarations and DigitalTwin writable (from service side) properties for this interface
//

static void Lenworks_interface_aInterface_Property_FanSpeedCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext);

//
//  Callback function declarations and DigitalTwin command names for this interface.
//

static void Lenworks_interface_aInterface_Command_BlinkCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext);

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct LENWORKS_INTERFACE_A_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

    double fanSpeed;

} LENWORKS_INTERFACE_A_INTERFACE_STATE;

static LENWORKS_INTERFACE_A_INTERFACE_STATE appState;

// Callback function to process the command "blink".
void Lenworks_interface_aInterface_Command_BlinkCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext)
{
    LENWORKS_INTERFACE_A_INTERFACE_STATE* interfaceState = (LENWORKS_INTERFACE_A_INTERFACE_STATE*)userInterfaceContext;
    LogInfo("LENWORKS_INTERFACE_A_INTERFACE: blink command invoked.");
    LogInfo("LENWORKS_INTERFACE_A_INTERFACE: blink request payload=<%.*s>, context=<%p>", (int)commandRequest->requestDataLen, commandRequest->requestData, interfaceState);

    // Get payload string
    char* requestData = (char*)malloc(commandRequest->requestDataLen + 1);
    if (requestData != NULL)
    {
        strncpy(requestData, (char*)commandRequest->requestData, commandRequest->requestDataLen);
        requestData[commandRequest->requestDataLen] = 0;
    }
    else
    {
        LogError("Failed to allocate memory for request payload");
    }

    // Parse request parameters from request payload string
    JSON_Value *jsonValue = NULL;
    jsonValue = json_parse_string((const char*)requestData);

    long interval = (long)json_value_get_number(jsonValue);

    // Invoke device command here
    unsigned int statusCode = 200;

    char responsePayload[MAX_MESSAGE_SIZE];

    LENWORKS_INTERFACE_A_BLINK_blinkResponse response;

    DIGITALTWIN_COMMAND_RESULT commandResult = Lenworks_interface_a_Command_Blink(interval, &response, &statusCode);

    // Serialize command response payload

    if (commandResult == DIGITALTWIN_COMMAND_OK &&
        Lenworks_interface_a_SerializeBlinkCommandResponse(&response, responsePayload, MAX_MESSAGE_SIZE))
    {
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, (const unsigned char*)responsePayload, statusCode);

    }
    else
    {
        LogError("Failed to execute blink command");
        const unsigned char errorResponse[] = "\"Failed to execute blink command\"";
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, errorResponse, statusCode);
    }

    free(requestData);

    if (jsonValue)
    {
        json_value_free(jsonValue);
    }

}

// DigitalTwinSample_ProcessCommandUpdate receives commands from the server.  This implementation acts as a simple dispatcher
// to the functions to perform the actual processing.
void Lenworks_interface_aInterface_ProcessCommandUpdate(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* dtCommandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* dtCommandResponse, void* userInterfaceContext)
{
    if (strcmp(dtCommandRequest->commandName, Lenworks_interface_aInterface_BlinkCommand) == 0)
    {
        Lenworks_interface_aInterface_Command_BlinkCallback(dtCommandRequest, dtCommandResponse, userInterfaceContext);
        return;
    }

    // If the command is not implemented by this interface, by convention we return a 501 error to server.
    LogError("LENWORKS_INTERFACE_A_INTERFACE: Command name <%s> is not associated with this interface", dtCommandRequest->commandName);
    const unsigned char commandNotImplementedResponse[] = "\"Requested command not implemented on this interface\"";
    (void)DigitalTwinClientHelper_SetCommandResponse(dtCommandResponse, commandNotImplementedResponse, 501);
}

// Lenworks_interface_aInterface_PropertyCallback is invoked when a property is updated (or failed) going to server.
// ALL property callbacks will be routed to this function and just have the userContextCallback set to the propertyName.
// Product code will potentially have context stored in this userContextCallback.
static void Lenworks_interface_aInterface_PropertyCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinReportedStatus, void* userContextCallback)
{
    if (digitalTwinReportedStatus == DIGITALTWIN_CLIENT_OK)
    {
        ReportProperty_Succeeded_Callback("Lenworks_interface_a", (const char*)userContextCallback);
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Updating property=<%s> succeeded", (const char*)userContextCallback);
    }
    else
    {
        ReportProperty_Error_Callback("Lenworks_interface_a", (const char*)userContextCallback);
        LogError("LENWORKS_INTERFACE_A_INTERFACE: Updating property=<%s> failed, error=<%s>", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinReportedStatus));
    }
}

// Processes a property update, which the server initiated, for 'fanSpeed' property.
static void Lenworks_interface_aInterface_Property_FanSpeedCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    LENWORKS_INTERFACE_A_INTERFACE_STATE* interfaceState = (LENWORKS_INTERFACE_A_INTERFACE_STATE*)userInterfaceContext;

    LogInfo("LENWORKS_INTERFACE_A_INTERFACE: fanSpeed property invoked...");
    LogInfo("LENWORKS_INTERFACE_A_INTERFACE: fanSpeed data=<%.*s>", (int)dtClientPropertyUpdate->propertyDesiredLen, dtClientPropertyUpdate->propertyDesired);

    DIGITALTWIN_CLIENT_PROPERTY_RESPONSE propertyResponse;

    // Version of this structure for C SDK.
    propertyResponse.version = DIGITALTWIN_CLIENT_PROPERTY_RESPONSE_VERSION_1;
    propertyResponse.responseVersion = dtClientPropertyUpdate->desiredVersion;

    // Parse string value and set updated property
    JSON_Value * jsonValue = json_parse_string((const char*)dtClientPropertyUpdate->propertyDesired);

    double newValue = json_value_get_number(jsonValue);

    bool isTypeValid = (json_value_get_type(jsonValue) == JSONNumber);

    if (isTypeValid)
    {
        interfaceState->fanSpeed = (double)newValue;

        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Updating fanSpeed property with new value <%s> ...", dtClientPropertyUpdate->propertyDesired);
        bool updateResult = Lenworks_interface_a_Property_FanSpeedCallback(interfaceState->fanSpeed);
 
        if (updateResult)
        {
            propertyResponse.statusCode = 200;
            propertyResponse.statusDescription = "fanSpeed property is updated successfully";
        }
        else
        {
            LogError("LENWORKS_INTERFACE_A_INTERFACE: failed to update writable property fanSpeed...");

            propertyResponse.statusCode = 500;
            propertyResponse.statusDescription = "failed to update writable property";
        }
    }
    else
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: Invalid desired value for fanSpeed, value should be Double");
        propertyResponse.statusCode = 500;
        propertyResponse.statusDescription = "Invalid desired value for fanSpeed, value should be Double";
    }
    json_value_free(jsonValue);

    // DigitalTwin_InterfaceClient_ReportPropertyAsync takes the DIGITALTWIN_CLIENT_PROPERTY_RESPONSE and returns information back to service.
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(appState.interfaceClientHandle, Lenworks_interface_aInterface_FanSpeedProperty, 
        dtClientPropertyUpdate->propertyDesired, dtClientPropertyUpdate->propertyDesiredLen, &propertyResponse,
        Lenworks_interface_aInterface_PropertyCallback, Lenworks_interface_aInterface_FanSpeedProperty);
    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin_InterfaceClient_ReportPropertyAsync for fanSpeed failed, error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }
    else
    {
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Successfully queued property update for fanSpeed");
    }
}

// Lenworks_interface_aInterface_ProcessPropertyUpdate receives updated properties from the server.  This implementation
// acts as a simple dispatcher to the functions to perform the actual processing.
static void Lenworks_interface_aInterface_ProcessPropertyUpdate(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    if (strcmp(dtClientPropertyUpdate->propertyName, Lenworks_interface_aInterface_FanSpeedProperty) == 0)
    {
        Lenworks_interface_aInterface_Property_FanSpeedCallback(dtClientPropertyUpdate, userInterfaceContext);
        return;
    }

    // If the property is not implemented by this interface, presently we only record a log message but do not have a mechanism to report back to the service
    LogError("LENWORKS_INTERFACE_A_INTERFACE: Property name <%s> is not associated with this interface", dtClientPropertyUpdate->propertyName);
}

// Lenworks_interface_aInterface_ReportPropertyAsync is a helper function to report a Lenworks_interface_a's properties.
// It invokes underlying DigitalTwin API for reporting properties and sets up its callback on completion.
DIGITALTWIN_CLIENT_RESULT Lenworks_interface_aInterface_ReportPropertyAsync(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* propertyName, const char* propertyData)
{
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(interfaceHandle, propertyName,
        (const unsigned char*)propertyData, strlen(propertyData), NULL,
        Lenworks_interface_aInterface_PropertyCallback, (void*)propertyName);

    if (result == DIGITALTWIN_CLIENT_OK)
    {
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Queued async report read only property for %s", propertyName);
        
    }
    else
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: Reporting property=<%s> failed, error=<%s>", propertyName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT Lenworks_interface_aInterface_Property_ReportName()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MESSAGE_SIZE];
    if (Lenworks_interface_a_SerializeNameProperty(payloadBuffer, MAX_MESSAGE_SIZE))
    {
        return Lenworks_interface_aInterface_ReportPropertyAsync(appState.interfaceClientHandle, Lenworks_interface_aInterface_NameProperty, payloadBuffer);
    }
    else
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: serialize read only property name failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Lenworks_interface_aInterface_Property_ReportAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple properties in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = Lenworks_interface_aInterface_Property_ReportName()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("DEVICE_INFO: Reporting properties failed.");
    }
    else
    {
        LogInfo("DEVICE_INFO: Queuing of all properties to be reported has succeeded");
    }

    return result;
}

// Lenworks_interface_aInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void Lenworks_interface_aInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    (void)userContextCallback;
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("Lenworks_interface_a");
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin successfully delivered telemetry message.");
    }
    else
    {
        SendTelemetry_Error_Callback("Lenworks_interface_a");
        LogError("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin failed to deliver telemetry message, error=<%s> ", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }
}

DIGITALTWIN_CLIENT_RESULT Lenworks_interface_aInterface_Telemetry_SendAll()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    DIGITALTWIN_CLIENT_RESULT result;

    char combinedMessage[MAX_MESSAGE_SIZE];
    char telemetryValue[MAX_MESSAGE_SIZE];

    // Send multiple telemetries in a single message
    sprintf(combinedMessage, "{");

    Lenworks_interface_a_SerializeTemperatureTelemetry(telemetryValue, MAX_MESSAGE_SIZE);

    sprintf(combinedMessage + strlen(combinedMessage), "\"%s\":%s,", Lenworks_interface_aInterface_TemperatureTelemetry, telemetryValue);

    Lenworks_interface_a_SerializeMagnetometerTelemetry(telemetryValue, MAX_MESSAGE_SIZE);

    sprintf(combinedMessage + strlen(combinedMessage), "\"%s\":%s", Lenworks_interface_aInterface_MagnetometerTelemetry, telemetryValue);

    sprintf(combinedMessage + strlen(combinedMessage), "}");

    if ((result = DigitalTwin_InterfaceClient_SendTelemetryAsync(appState.interfaceClientHandle, (unsigned char*)combinedMessage, strlen(combinedMessage),
        Lenworks_interface_aInterface_TelemetryCallback, NULL)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending telemetry.");
    }

    return result;
}

// Lenworks_interface_aInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void Lenworks_interface_aInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("Lenworks_interface_aInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE Lenworks_interface_aInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(LENWORKS_INTERFACE_A_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(Lenworks_interface_aInterfaceId,  Lenworks_interface_aInterfaceInstanceName, Lenworks_interface_aInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", Lenworks_interface_aInterfaceId, Lenworks_interface_aInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback(interfaceHandle, Lenworks_interface_aInterface_ProcessPropertyUpdate, (void*)&appState)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        Lenworks_interface_aInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetCommandsCallback(interfaceHandle, Lenworks_interface_aInterface_ProcessCommandUpdate, (void*)&appState)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("LENWORKS_INTERFACE_A_INTERFACE: DigitalTwin_InterfaceClient_SetCommandsCallbacks failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        Lenworks_interface_aInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("LENWORKS_INTERFACE_A_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", Lenworks_interface_aInterfaceId, Lenworks_interface_aInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void Lenworks_interface_aInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
